export enum CalculusOperationKind {
  DERIVATIVE = "DERIVATIVE",
  NUMERIC_DERIVATIVE = "NUMERIC_DERIVATIVE",
  INTEGRAL = "INTEGRAL",
  INTEGRATE = "INTEGRATE",
  LIMIT = "LIMIT",
  TAYLOR = "TAYLOR",
  SUM = "SUM",
  PRODUCT = "PRODUCT",
}
