export enum CalculatorButtonInsertionBehavior {
  INSERT_CHARACTER = "INSERT_CHARACTER",
  INSERT_OPERATOR = "INSERT_OPERATOR",
  INSERT_FUNCTION = "INSERT_FUNCTION",
  INSERT_CONSTANT = "INSERT_CONSTANT",
  INSERT_VARIABLE = "INSERT_VARIABLE",
  INSERT_TEMPLATE = "INSERT_TEMPLATE",
  INSERT_WRAPPED_SELECTION = "INSERT_WRAPPED_SELECTION",
}
