import { ScientificConstant } from "../../domain/model/ScientificConstant";
import { ScientificConstantCategory } from "../../domain/model/ScientificConstantCategory";

export const atomicParticleConstants: readonly ScientificConstant[] = [
    new ScientificConstant(
        "electronMass",
        "m_e",
        "Electron mass",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "9.1093837015e-31",
        "kg",
        "The rest mass of an electron.",
        "CODATA 2018",
        ["me"],
    ),
    new ScientificConstant(
        "protonMass",
        "m_p",
        "Proton mass",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "1.67262192369e-27",
        "kg",
        "The rest mass of a proton.",
        "CODATA 2018",
        ["mp"],
    ),
    new ScientificConstant(
        "neutronMass",
        "m_n",
        "Neutron mass",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "1.67492749804e-27",
        "kg",
        "The rest mass of a neutron.",
        "CODATA 2018",
        ["mn"],
    ),
    new ScientificConstant(
        "atomicMassConstant",
        "u",
        "Unified atomic mass constant",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "1.66053906660e-27",
        "kg",
        "One twelfth of the mass of a carbon-12 atom.",
        "CODATA 2018",
        ["amu"],
    ),
    new ScientificConstant(
        "bohrRadius",
        "a₀",
        "Bohr radius",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "5.29177210903e-11",
        "m",
        "The most probable distance between the nucleus and the electron in a hydrogen atom.",
        "CODATA 2018",
        ["a0"],
    ),
    new ScientificConstant(
        "rydbergConstant",
        "R∞",
        "Rydberg constant",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "10973731.568160",
        "m⁻¹",
        "The highest wavenumber in the hydrogen spectral series.",
        "CODATA 2018",
        ["Rinf"],
    ),
    new ScientificConstant(
        "fineStructureConstant",
        "α",
        "Fine-structure constant",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "0.0072973525693",
        null,
        "A dimensionless coupling constant characterizing the strength of electromagnetic interaction.",
        "CODATA 2018",
        [],
    ),
    new ScientificConstant(
        "hartreeEnergy",
        "E_h",
        "Hartree energy",
        ScientificConstantCategory.ATOMIC_AND_PARTICLE,
        "4.3597447222071e-18",
        "J",
        "The atomic unit of energy.",
        "CODATA 2018",
        ["Eh"],
    ),
];
